# Generated by Django 4.2.28 on 2026-05-02 06:51

import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_contact'), ('catalog', '0003_tutorial_and_tuner'), ('catalog', '0004_alter_tutorial_optional_fields'), ('catalog', '0005_instrument_show_brightness_control'), ('catalog', '0006_remove_expert_media_fields'), ('catalog', '0007_branding'), ('catalog', '0008_branding_contact_emails_and_media_audio_cleanup'), ('catalog', '0009_branding_split_contact_email'), ('catalog', '0010_remove_branding_contact_notification_emails'), ('catalog', '0011_alter_branding_id_alter_branding_logo_and_more'), ('catalog', '0014_instrument_model_3d_delete_media')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('playing_technique', models.TextField(blank=True)),
                ('cultural_significance', models.TextField(blank=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='instruments/images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='catalog.category')),
                ('show_brightness_control', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('model_3d', '3D Model'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='instruments/media/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.instrument')),
            ],
            options={
                'ordering': ['media_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TunerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_name', models.CharField(default='Standard', max_length=100)),
                ('notes', models.JSONField(default=list, help_text="List of note names, e.g. ['E2', 'A2', 'D3', 'G3', 'B3', 'E4']")),
                ('frequencies', models.JSONField(default=list, help_text='List of frequencies in Hz, e.g. [82.41, 110.00, 146.83, 196.00, 246.94, 329.63]')),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuner_config', to='catalog.instrument')),
            ],
            options={
                'ordering': ['-is_default', 'tuning_name'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('instructor_name', models.CharField(blank=True, default='', max_length=150)),
                ('duration', models.CharField(blank=True, default='', help_text="e.g., '12:30'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='catalog.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expertise', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('detailed_bio', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/photos/')),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instruments', models.ManyToManyField(blank=True, related_name='experts', to='catalog.instrument')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='BAJAGHAR', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_alt', models.CharField(blank=True, default='BAJAGHAR logo', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_emails', models.TextField(blank=True, default='info@bajanepal.com', help_text='Comma-separated email addresses that receive contact form notifications')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
            },
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('model_3d', '3D Model'), ('video', 'Video')], max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@bajanepal.com', help_text='Single public email shown in the footer and contact area', max_length=254),
        ),
        migrations.AddField(
            model_name='branding',
            name='contact_notification_emails',
            field=models.TextField(blank=True, default='admin@bajanepal.com,nabin@bajanepal.com', help_text='Comma-separated email addresses that receive contact form notifications'),
        ),
        migrations.RemoveField(
            model_name='branding',
            name='contact_emails',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='contact_notification_emails',
        ),
        migrations.AlterField(
            model_name='branding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo',
            field=models.FileField(blank=True, help_text='Supports: JPG, PNG, GIF, WEBP, SVG', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Upload a valid image file (JPG, PNG, GIF, WEBP, or SVG)')]),
        ),
        migrations.AlterField(
            model_name='tunerconfiguration',
            name='notes',
            field=models.JSONField(default=list, help_text='List of note names, e.g. ["E2", "A2", "D3", "G3", "B3", "E4"]'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Supports: GLB, GLTF, BIN', null=True, upload_to='instruments/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'bin'], message='Upload a valid 3D model file (GLB, GLTF, or BIN)')]),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
