# Generated by Django 4.2.28 on 2026-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_branding_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='show_tuner',
            field=models.BooleanField(default=False),
        ),
    ]
