# Generated by Django 4.2.28 on 2026-05-10 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_instrument_show_tuner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='caption_en',
            field=models.FileField(blank=True, help_text='English captions (VTT or SRT format). Optional for YouTube videos.', null=True, upload_to='tutorials/captions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt', 'srt'], message='Upload a valid caption file (VTT or SRT format)')]),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='caption_ne',
            field=models.FileField(blank=True, help_text='Nepali captions (VTT or SRT format). Optional for YouTube videos.', null=True, upload_to='tutorials/captions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt', 'srt'], message='Upload a valid caption file (VTT or SRT format)')]),
        ),
    ]
