# Generated by Django 4.2.28 on 2026-05-02 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_branding_contact_notification_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo',
            field=models.FileField(blank=True, help_text='Supports: JPG, PNG, GIF, WEBP, SVG', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Upload a valid image file (JPG, PNG, GIF, WEBP, or SVG)')]),
        ),
        migrations.AlterField(
            model_name='tunerconfiguration',
            name='notes',
            field=models.JSONField(default=list, help_text='List of note names, e.g. ["E2", "A2", "D3", "G3", "B3", "E4"]'),
        ),
    ]
