# Generated by Django 4.2.28 on 2026-05-02 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_branding_id_alter_branding_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Supports: GLB, GLTF, BIN', null=True, upload_to='instruments/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'bin'], message='Upload a valid 3D model file (GLB, GLTF, or BIN)')]),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
