# Generated by Django 4.2.28 on 2026-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_contact_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='logo_alt_ne',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='name_ne',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ne',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ne',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='achievements_ne',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='bio_ne',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='detailed_bio_ne',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='expertise_ne',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='name_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='cultural_significance_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='description_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='history_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='materials_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='name_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='playing_technique_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='region_ne',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='show_tuner',
        ),
        migrations.RemoveField(
            model_name='learningcontent',
            name='content_ne',
        ),
        migrations.RemoveField(
            model_name='learningcontent',
            name='title_ne',
        ),
        migrations.RemoveField(
            model_name='tunerconfiguration',
            name='tuning_name_ne',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='caption_ne',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='description_ne',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='instructor_name_ne',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='title_ne',
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='catalog_log_usernam_73462d_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='catalog_log_ip_addr_b9ebd8_idx')],
            },
        ),
    ]
