# Generated by Django 4.2.28 on 2026-05-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_tunerconfiguration_multiple_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunerconfiguration',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Optional tuning tips or setup instructions shown on the tuner page'),
        ),
        migrations.AddField(
            model_name='tunerconfiguration',
            name='instructions_ne',
            field=models.TextField(blank=True, default='', help_text='Optional Nepali tuning tips or setup instructions shown on the tuner page'),
        ),
    ]
